# Generated by Django 3.2.9 on 2022-06-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_counter',
            field=models.IntegerField(default=0, verbose_name='Количество обновленией'),
        ),
    ]
